### ISSUE TITLE
有關Adv Player 對故事標題的處理

### ISSUE THREAD

**Issue by Cpk0521** [DreamGallery/WDS-Translation-Csv#5]
參考了一下SC翻譯文件做法

現在支持這樣子的方式去作`標題的處理`以及`顯示一些資訊`
![image](https://github.com/user-attachments/assets/8a31f6fe-e298-4c09-8682-b8c4818f9116)

效果會是這樣
![image](https://github.com/user-attachments/assets/8d7f8b09-8a51-49bb-acd3-999cc582fa6f)

當然沒有寫也不會有任何問題 大小寫也沒差
| Parameters  | 說明 | - |
| :-------------: | :-------------: | :-------------:|
|translator  | 翻譯者 | 暫時沒有用途 不會顯示 可能之後會用到? |
|proofreader  | 校對者  | 同上 |
|TLTitle| 故事標題 | 會替代`日文故事標題`顯示  |
|Title| 同上 | 同上 只是名字不同 |
|info| 想顯示出來的文字 | 或許會有除了`翻譯`及`校對`之外的文字 所以偷個懶想顯示什麼寫什麼|

**Comment by DreamGallery** [comment]
sc/gkmas那边的确像这样会把一些信息添加到csv最后面，非常感谢，辛苦大佬了
今天有空我也去把现有的csv都批量修改一下看看

**Comment by Cpk0521** [comment]
辛苦了
